### ISSUE TITLE
Recover or re-create `ppc-testresults.dat.bz2`

### ISSUE THREAD

**Issue by ianfixes** [emaculation/macemu#102]
From [`doc/PowerPC-Testsuite.md`](https://github.com/emaculation/SheepShaver/blob/master/doc/PowerPC-Testsuite.md): 
> It is recommended that you first run the tester on a native PowerPC platform to generate a results file. For reference, here is the [[this>projects/ppctester/files/ppc-testresults.dat.bz2|PowerPC Emulator Tester results file]] I use for SheepShaver. This was generated with AltiVec tests enabled. This is for revision 1.30+ of the file. md5sum is: ''3e29432abb6e21e625a2eef8cf2f0840''.

We should do that, and save the file here for posterity.

(Note: this issue was originally https://github.com/emaculation/SheepShaver/issues/10)

**Comment by rakslice** [comment]
What even is this testsuite? Is it actually in the codebase somewhere?

**Comment by rakslice** [comment]
Oh, I get it, it's `test-powerpc.cpp`.

It basically has two modes; if you run it on a native PowerPC system, it tests the local CPU and writes the results to a file. Otherwise, it takes a results file, does a test on the emulated CPU (using the JIT if you pass `--jit` first) and compares the results with the results file.

It has no concept of anything but real (one-to-one with the host system) memory addresses.

**Comment by ianfixes** [comment]
Correct, this issue is to track getting/generating a copy of that results file so that we could actually test against it in this repo.

**Comment by rakslice** [comment]
There's an apparent archived copy at http://web.archive.org/web/20060217123013/http://www.gibix.net/projects/ppctester/files/ppc-testresults.dat.bz2

**Comment by ianfixes** [comment]
This was a good lead, but upon downloading every version they had I didn't get the right MD5

```console
$ md5 ppc-testresults*
MD5 (ppc-testresults (1).dat.bz2) = 60172863f951c72e1ee7e01d54ed6db3
MD5 (ppc-testresults (2).dat.bz2) = 60172863f951c72e1ee7e01d54ed6db3
MD5 (ppc-testresults (3).dat.bz2) = 60172863f951c72e1ee7e01d54ed6db3
MD5 (ppc-testresults (4).dat.bz2) = 60172863f951c72e1ee7e01d54ed6db3
MD5 (ppc-testresults (5).dat.bz2) = 60172863f951c72e1ee7e01d54ed6db3
MD5 (ppc-testresults.dat.bz2) = 60172863f951c72e1ee7e01d54ed6db3
```

I wonder if @cebix or @FreeBSD-pzn can comment on its suitability of this other version of the test file

**Comment by rakslice** [comment]
Try md5summing the file in the archive :D

**Comment by ianfixes** [comment]
🎉 👍 🥇 !!!

**Comment by ianfixes** [comment]
This is excellent, I hadn't imagined that this file would ever turn up.  

I've opened #139 to track making actual use of this file as part of CI
