### ISSUE TITLE
emul_ppc.cpp: complete instruction set (2)

### ISSUE THREAD

**Issue by retokromer** [emaculation/macemu#107]
# Complete PowerPC instructions set

## Instructions to add

- [ ] addme
- [ ] addmeo
- [ ] addze
- [ ] addzeo
- [ ] dcbst
- [ ] dcbt
- [ ] dcbtst
- [ ] divwuo
- [ ] fabs
- [ ] fadd
- [ ] fadds
- [ ] fcmpo
- [ ] fcmpu
- [ ] fctiw
- [ ] fctiwz
- [ ] fdiv
- [ ] fdivs
- [ ] fmadd
- [ ] fmadds
- [ ] fmr
- [ ] fmsub
- [ ] fmsubs
- [ ] fmul
- [ ] fmuls
- [ ] fnabs
- [ ] fneg
- [ ] fnmadd
- [ ] fnmadds
- [ ] fnmsub
- [ ] fnmsubs
- [ ] fres
- [ ] frsp
- [ ] frsqrte
- [ ] fsel
- [ ] fsqrt
- [ ] fsqrts
- [ ] fsub
- [ ] fsubs
- [ ] lfdu
- [ ] lfdux
- [ ] lfdx
- [ ] lfs
- [ ] lfsu
- [ ] lfsux
- [ ] lfsx
- [ ] lhbrx
- [ ] lwbrx
- [ ] mcrfs
- [ ] mcrxr
- [ ] mtfsb0
- [ ] mtfsb1
- [ ] mtfsfi
- [ ] mulhwu
- [ ] mullwo
- [ ] nego
- [ ] sc
- [ ] stfdu
- [ ] stfdux
- [ ] stfdx
- [ ] stfs
- [ ] stfsu
- [ ] stfsux
- [ ] stfsx
- [ ] sthbrx
- [ ] stwbrx
- [ ] subfo
- [ ] subfme
- [ ] subfmeo
- [ ] subfze
- [ ] subfzeo
- [ ] tw
- [ ] twi

## Instructions to check

- [ ] crxor
- [ ] creqv

## Reference

https://github.com/emaculation/SheepShaver/blob/d7c8d527a9471a18f15ff55c57e2222290ac28d8/src/emul_ppc/emul_ppc.cpp#L21-L99

**Comment by ianfixes** [comment]
I will check this when i get back to my computer, but i think if you copy
the text of the issue, it will put the markdown source on the clipboard. If
not, I'll unarchive and copy it over for you

**Comment by retokromer** [comment]
No, only the raw text is copied without any formatting. It’s not an urgent matter on my end, because I’m leaving and for the coming two weeks I’ll work out of office.

**Comment by ianfixes** [comment]
updated
