### ISSUE TITLE
Add shoebill to emaculation?

### ISSUE THREAD

**Issue by davewongillies** [emaculation/macemu#110]
I'm not sure if this is something that you're interested in, but I thought perhaps it could be a good to add [shoebill](https://github.com/pruten/shoebill) to this Github org? I'm not sure if anyone is out there patching it much but it at least looks like it could do with some love and care to get it compiling on recent OSes now that the maintainer isn't able to work on it due to contractual reasons. I'd be happy to help out with getting CI working for it.

**Comment by ianfixes** [comment]
I am open to this idea, but I don't feel comfortable doing that without hearing from the current maintainer.  

Strictly speaking, the `emaculation` GitHub organization that I created is a set of _forks_ of the original [cebix/macemu](https://github.com/cebix/macemu) repo.  Although @cebix had graciously provided his source code on GitHub, he is seemingly and understandably not able to devote much time to reviewing or merging pull requests, setting up CI, etc -- things that would enable the more active members of its community to carry the torch on this project.  @cebix has accepted my invitation to be an admin on this project, but I haven't heard from him on whether the official home for this code will change; the next step would be to invite some of the owners of the most prolific forks (e.g. @kanjitalk755) to be admins here.

So it makes a lot of sense to fork a somewhat-abandoned project here, but the goal of such a move should be to _centralize_ a community of developers, not split an existing one.  What's the best way to pose that question to the shoebill community?

**Comment by kanjitalk755** [comment]
Reference: My repo can be built with macOS10.14/Xcode10.

https://github.com/kanjitalk755/shoebill

```
$ make && open gui/build/Release/Shoebill.app
```

**Comment by ianfixes** [comment]
@kanjitalk755 the graph for shoebill suggests that you are indeed the current steward of that code.  https://github.com/pruten/shoebill/network

Would you like me to bring that over for you?  Also, may I make you an admin of this github organization? My only pressing to-do item for any of these repos is to set up functioning cross-platform builds in CI (my area of expertise) then step back.

**Comment by kanjitalk755** [comment]
I don't want to be an admin.
I just prepared Shoebill that can be built in the current environment.

**Comment by ianfixes** [comment]
I don't really want to be an admin either, I'm in no way qualified to contribute or evaluate changes to the emulator itself.  I just need someone who can carry that torch -- even briefly -- and get it closer to whoever the most qualified person is to be an admin.  If not you, who would you recommend?

That's part of why I put everything in a GitHub organization, because I know that individually we aren't in a position to make long-term commitments to this codebase.

**Comment by kanjitalk755** [comment]
Sorry, I think no one to recommend.

**Comment by ianfixes** [comment]
@davewongillies after some discussion in https://github.com/pruten/shoebill/issues/13 it looks like we will be forking Shoebill here!

**Comment by ianfixes** [comment]
Forked at https://github.com/emaculation/shoebill
Appveyor and TravisCI have been enabled for that repo.

@davewongillies I set up placeholders for the CI work
* https://github.com/emaculation/shoebill/issues/1
* https://github.com/emaculation/shoebill/issues/2
* https://github.com/emaculation/shoebill/issues/3

**Comment by ianfixes** [comment]
@kanjitalk755 just to be clear about your vision here, are you saying you'd prefer to contribute pull requests to this repository instead of having other people submit pull requests to your own fork?

**Comment by kanjitalk755** [comment]
I think it's good to submit a PR to emaculation/shoebill instead of my fork.

**Comment by ianfixes** [comment]
Understood.  Do you feel similarly about https://github.com/emaculation/macemu ?

**Comment by kanjitalk755** [comment]
Currently, BII and SS distributed at https://www.emaculation.com/forum/ are built from my fork.
Therefore, if someone want to reflect in the distribution there, I think the PR to my fork is good.
