### ISSUE TITLE
Real addressing mode for the emulator

### ISSUE THREAD

**Issue by ianfixes** [emaculation/macemu#125]
From the [original project](https://github.com/cebix/macemu)'s [`BasiliskII/src/MacOSX/ToDo.html`](https://github.com/cebix/macemu/blob/0a7fe2eaf8e88a458836c3ec1f382906b253d85a/BasiliskII/src/MacOSX/ToDo.html):

> Real addressing mode for the emulator. Mike Sliczniak had done most of the work, but with real addressing the emulator just crashes for me.

No further information is available; it's also possible that this issue has been addressed in the time since that 2007-07-14 revision.

**Comment by SegHaxx** [comment]
Real addressing mode is obsolete, newer OSs aren't allowing it because its a security risk.

It's only required in Basilisk II if you're running on real 68k hardware and OSX doesn't run on those anyway. :)

I recommend closing this.

**Comment by ianfixes** [comment]
Sounds good to me
