### ISSUE TITLE
Recover or re-create `ppc-testresults.dat.bz2`

### ISSUE THREAD

**Issue by FreeBSD-pzn** [emaculation/macemu#132]
Hi!
Do you still need recover or re-create `ppc-testresults.dat.bz2`?
Now I can to try make it on a macmini G4 with OSX 10.5 (Xcode 3.1) or on a iBook G4 with OSX 10.4 (Xcode 2.5).
Oleg

**Comment by FreeBSD-pzn** [comment]
Sorry, I don't find #102 issue.
Please move this issue to the #102 .
Thanks.

**Comment by ianfixes** [comment]
Thank you Oleg!  Yes, let's continue talking about this in #102
