### ISSUE TITLE
Add "Team Discussions"

### ISSUE THREAD

**Issue by SegHaxx** [emaculation/macemu#148]
Hey it seems like we could really do with adding "Discussions" to this project. So we can coordinate more general discussions about the future of the project without scattering it across numerous issues and PRs. :)

Incidentally I have submitted a Basilisk II flatpak to Flathub. This will get Basilisk II back in to the hands of users on all current Linux desktops. https://github.com/flathub/flathub/pull/1986

Yes I do have plans of making a SheepShaver flatpak too, but BII was enough work as it is for now. :)

**Comment by ianfixes** [comment]
I'm not sure if this is still a question, but my preference would be to continue using the gitter channel: https://gitter.im/emaculation/macemu

**Comment by SegHaxx** [comment]
Sorry didn't notice the link to that until later.
